### ISSUE TITLE
why we need to use a state to store the client (in App.jsx)?

### ISSUE THREAD

**Issue by trollepierre** [cozy/cozy-flagship-app#216]
I still don't understand why we need to use a state to store the client. But since this code was already there, it should not be handled in this PR. but @Ldoppea / @trollepierre / @acezard we need to think about it

_Originally posted by @Crash-- in https://github.com/cozy/cozy-react-native/pull/203#discussion_r870288203_

**Comment by acezard** [comment]
This allows us to wait for the client before opening the app, else it will crash. 
This will be rewritten with the future redux rewrite
